---
- name: Install Samba (RedHat)
  ansible.builtin.dnf:
    name: samba
    state: present
  become: true
  tags: [samba, install]

- name: Deploy smb.conf (RedHat)
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: restart samba
  tags: [samba, configure]
