---
unbound_root_hints_url: "https://www.internic.net/domain/named.root"
unbound_port:       5335
unbound_do_ip4:     "yes"
unbound_do_ip6:     "no"
unbound_prefer_ip6: "no"
unbound_do_udp:     "yes"
unbound_do_tcp:     "yes"
unbound_num_threads: 1
unbound_so_rcvbuf:  "1m"
