---
- name: Import directory setup tasks
  ansible.builtin.import_tasks: dirs.yml

- name: Import config deploy tasks
  ansible.builtin.import_tasks: configure.yml

- name: Import container tasks
  ansible.builtin.import_tasks: container.yml

- name: Import OTEL schema bootstrap tasks
  ansible.builtin.import_tasks: otel_schema.yml
