---
- name: Configure local system users and git credentials
  ansible.builtin.include_tasks: configure_user.yml
  loop: "{{ system_users }}"
  loop_control:
    loop_var: user_item
  when: inventory_hostname in groups['dev_nodes']
