---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  become: true
  listen: "restart nginx"

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true
  listen: "reload nginx"
