" ~/.vimrc — managed by Ansible (user_dotfiles role)

"" Basics
set number
set wrap
set encoding=utf-8
set mouse=a
set wildmenu
set lazyredraw
set showmatch
set laststatus=2
set ruler

"" Looks
try
  colorscheme slate
catch
endtry

syntax enable
filetype plugin indent on

"" Tabs
set tabstop=2
set expandtab
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

"" Misc
set history=500
set hlsearch
